services:

  redis:
    restart: always
    image: redis/redis-stack:latest
    volumes:
      - redis_volume:/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  postgres:
    restart: always
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -V" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: -p ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

volumes:
  redis_volume:
  postgres_volume: