"""Initial tables

Revision ID: b3c4eebd6d3b
Revises:
Create Date: 2025-06-28 23:49:55.336495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import store

# revision identifiers, used by Alembic.
revision: str = "b3c4eebd6d3b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "password",
            store.accessors.user.models.PasswordHash(length=128),
            nullable=False,
        ),
        sa.Column("role", store.accessors.user.models.Role(length=28), nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        schema="shift",
    )
    op.create_table(
        "salaries",
        sa.Column("salary", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["shift.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="shift",
    )
    op.create_index(
        "idx_user_date", "salaries", ["user_id", "date"], unique=True, schema="shift"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_date", table_name="salaries", schema="shift")
    op.drop_table("salaries", schema="shift")
    op.drop_table("users", schema="shift")
    # ### end Alembic commands ###
